services:
  # Nodejs application
  node-api:
    container_name: node-api
    build:
      context: ./node-api
      dockerfile: Dockerfile
    init: true
    user: root
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=psql_db
      - QUEUE_HOST=rabbitmq
      - QUEUE_PORT=5672
      - DB_PORT=5432
      - DB_USER=superuser
      - DB_PASSWORD=superpassword
      - APP_PORT=8000
    networks:
      - db_network
      - rabbitmq_net
      - kafka_net
      - app_network
    command: sh -c "yarn install && yarn run generate-migration && yarn run migrate && yarn dev"
    depends_on:
      - psql_db
      - redis_cache
      - rabbitmq
      - kafka

  # Go application
  go-api:
    container_name: go-api
    build:
      context: ./go-api
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    init: true
    user: root
    environment:
      - GO111MODULE=on
      - DB_HOST=psql_db
      - QUEUE_HOST=rabbitmq
      - QUEUE_PORT=5672
      - QUEUE_NAME=micro-services-queue
      - QUEUE_PASSWORD=guest
      - QUEUE_USER=guest
      - APP_PORT=8001
    networks:
      - db_network
      - rabbitmq_net
      - kafka_net
      - app_network
    command:
      - sh
      - -c
      - |-
        sleep 1 && \
        CompileDaemon --build="go build -o go-api ." --command="./go-api"
    depends_on:
      - psql_db
      - redis_cache
      - rabbitmq
      - kafka

  # Python application
  python-api:
    container_name: python-api
    build:
      context: ./python-api
      dockerfile: Dockerfile
    volumes:
      - ./python-api:/app
      - /app/.venv
    ports:
      - "8002:8002"
    environment:
      - DB_HOST=psql_db
      - QUEUE_HOST=rabbitmq
      - QUEUE_PORT=5672
    networks:
      - db_network
      - rabbitmq_net
      - kafka_net
      - app_network
    command: sh -c "uvicorn python_api.main:app --port=8002 --host=0.0.0.0 --reload --log-level debug"
    depends_on:
      - psql_db
      - redis_cache
      - rabbitmq
      - kafka

  # PostgreSQL database
  psql_db:
    container_name: psql_db
    image: postgres:15.5-alpine3.19
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: main
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Redis database
  redis_cache:
    container_name: redis_cache
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - db_network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Nginx instance
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    # command: sh -c "chown -R nginx:nginx /var/lib/nginx"
    networks:
      - app_network
    depends_on:
      - node-api
      - go-api
      - python-api

  # Zookeeper instance
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: unless-stopped
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo:2888:3888
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka_net

  # Kafka instance
  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "baeldung:1:1"
    depends_on:
      - zookeeper
    networks:
      - kafka_net

  # RabbitMQ instance
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - rabbitmq_net

volumes:
  postgres_data:
  redis_data:

networks:
  kafka_net:
    driver: bridge
  rabbitmq_net:
    driver: bridge
  db_network:
    driver: bridge
  app_network:
    driver: bridge
